pipeline {
    agent any
    tools {
        maven 'maven3'
        jdk 'jdk8'
    }
    stages {
        stage('Build') {
        dir('restassured-asciidoctor')
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            dir('restassured-asciidoctor')
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh 'echo Delivered'
            }
        }
    }
}