pipeline {
    agent any
    tools {
        maven 'maven3'
        jdk 'jdk8'
    }
    stages {
        stage('Build') {
            steps {
                dir('restassured-asciidoctor') {
                    sh 'mvn -B -DskipTests clean package'
                }
            }
        }
        stage('Unit Test') {
            steps {
                dir('restassured-asciidoctor'){
                    sh 'mvn surefire:test'
                }
            }
        }
        stage('Integration Tets') {
            steps {
                dir('restassured-asciidoctor'){
                    sh 'mvn failsafe:integration-test@integration-test  org.asciidoctor:asciidoctor-maven-plugin:process-asciidoc@generate-doc'
                }
            }
            post {
                always {
                    junit 'restassured-asciidoctor/target/failsafe-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh 'echo Delivered'
            }
        }
    }
}